version: '2'
services:
  postgres:
    image: 'postgis/postgis:13-3.1'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
